name: Docker Image Hello Word

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      uses: docker/build-push-action@v6

      with:
        context: ./app
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ci_cd:latest

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }} 
          username: aluno
          key: ${{ secrets.SERVER_KEY }}
          debug: true
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/ci_cd:latest
            docker stop my_app || true
            docker rm my_app || true
            docker run -d -p 8080:80 --name my_app ${{ secrets.DOCKER_USERNAME }}/ci_cd:latest 
